export const SET_USER = "SET_USER";
export const STREAMS_FETCHED = "STREAMS_FETCHED";
export const STREAM_FETCHED = "STREAM_FETCHED";
export const STREAM_CREATED = "STREAM_CREATED";
export const STREAM_UPDATED = "STREAM_UPDATED";
export const STREAM_DELETED = "STREAM_DELETED";